[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  BUNDLE_PATH = "vendor/bundle"

[context.production.environment]
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-functions-install-core-packages"

[build.processing]
  skip_processing = true

[context.production]
  command = "sudo apt-get update && sudo apt-get install -y libpq-dev && gem install pg && bundle install && bundle exec jekyll build"
