[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[context.production.environment]
  RUBY_VERSION = "3.1.2"
  BUNDLE_PATH = "vendor/bundle"
  RAILS_ENV = "production"

[build.environment]
  BUNDLE_PATH = "vendor/bundle"
  RUBY_VERSION = "3.1.2"
  RAILS_ENV = "production"

[build.lifecycle]
  onBuildCommand = "apt-get install -y libpq-dev"

[build.postbuild]
  command = "bundle exec rails assets:precompile"
