meta_name: "The Surf Course"
meta_title: "The Surf Course - trouve ta planche et ta combi"
meta_description: "Trouve la meilleure planche et combi utilisant notre formulaire."
meta_image: "ogimage.png" # should exist in `app/assets/images/`
# twitter_account: "@thesurfcourse"   # required for Twitter Cards
